imports:
    - { resource: "admin.yml" }

pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopProductSpecificTierPriceRules: CoreShop\Bundle\TierPricingBundle\CoreExtension\ProductSpecificTierPriceRules

jms_serializer:
    metadata:
        directories:
            coreshop-tier-pricing:
                namespace_prefix: "CoreShop\\Component\\TierPricing"
                path: "@CoreShopTierPricingBundle/Resources/config/serializer"