image: php:7.0

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install mysql driver
  - docker-php-ext-install pdo_mysql

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Remove cloned stuff
  - rm -rf $CI_PROJECT_DIR/
  - mkdir -p $CI_PROJECT_DIR/
  - git clone https://github.com/pimcore/pimcore.git $CI_PROJECT_DIR

  # add config templates
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp app/config/parameters.example.yml app/config/parameters.yml

  # install composer - HHVM isn't officially PHP 7 compatible - see https://github.com/composer/composer/issues/4976
  - if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then php composer.phar install; fi
  - if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then php composer.phar install --ignore-platform-reqs; fi

  # Include CoreShop with specific commit to test it, because of Pimcore's way of dealing not as dependency,
  # this test is kinda stupid
  - php composer.phar require coreshop/coreshop $TRAVIS_COMMIT

  # Install all project dependencies
  - php composer.phar install

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: coreshop_phpunit
  MYSQL_ROOT_PASSWORD: root
  GIT_STRATEGY: none

# We test PHP7.0 (the default) with MySQL
test:mysql:
  script:
    - cd $CI_PROJECT_DIR/vendor/coreshop/coreshop/tests
    - run-tests.sh

# We test PHP7.1 with MySQL, but we allow it to fail
test:php7.1:mysql:
  image: php:7.1
  script:
    - cd $CI_PROJECT_DIR/vendor/coreshop/coreshop/tests
    - run-tests.sh
