image: php:7.0

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git zlib1g-dev libicu-dev g++ libmcrypt-dev libldap2-dev libxml2-dev bzip2 unzip memcached ntpdate libxrender1 libfontconfig1 -yqq

  # Copy PHP INI
  - cp .gitlab-ci/php.ini /usr/local/etc/php/php.ini

  # Install PHP Extensions
  - docker-php-ext-install pdo_mysql
  - docker-php-ext-configure intl
  - docker-php-ext-install intl
  - docker-php-ext-install zip
  - docker-php-ext-install mcrypt
  - docker-php-ext-install -j$(nproc) gd
  - docker-php-ext-install bcmath
  - docker-php-ext-install curl
  - docker-php-ext-install exif
  - docker-php-ext-configure imap --with-kerberos --with-imap-ssl
  - docker-php-ext-install imap
  - docker-php-ext-configure ldap
  - docker-php-ext-install ldap
  - docker-php-ext-install xml
  - docker-php-ext-install simplexml
  - docker-php-ext-install mbstring

  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  # Remove cloned stuff
  - rm -rf $CI_PROJECT_DIR
  - mkdir -p $CI_PROJECT_DIR/
  - cd $CI_PROJECT_DIR
  - git clone https://github.com/pimcore/pimcore.git $CI_PROJECT_DIR

   # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Add Composer Private Repo
  - php composer.phar config repositories.coreshop vcs ssh://git@git.lineofcode.at:2020/CoreShop/CoreShop2.git

  # add config templates (needed for composer install, otherwise symfony throws an exception)
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp app/config/parameters.example.yml app/config/parameters.yml

  # install composer
  - php composer.phar install --ignore-platform-reqs
  - php composer.phar require symfony/symfony:dev-master --ignore-platform-reqs

  # Install CoreShop
  # Include CoreShop with specific commit to test it, because of Pimcore's way of dealing not as dependency,
  # this test is kinda stupid
  - php composer.phar require coreshop/core-shop:dev-master#$CI_COMMIT_REF  --ignore-platform-reqs

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: coreshop_phpunit
  MYSQL_ROOT_PASSWORD: root
  CORESHOP_MYSQL_HOST: mysql
  CORESHOP_MYSQL_DB: coreshop_phpunit
  CORESHOP_MYSQL_USER: root
  CORESHOP_MYSQL_PWD: root

# We test PHP7.0 (the default) with MySQL
test:mysql:
  script:
    - vendor/bin/phpunit -c vendor/coreshop/core-shop/tests/config/phpunit.xml --bootstrap vendor/coreshop/core-shop/tests/bootstrap.php vendor/coreshop/core-shop/tests/AllTests

# We test PHP7.1 with MySQL, but we allow it to fail
test:php7.1:mysql:
  image: php:7.1
  script:
    - vendor/bin/phpunit -c vendor/coreshop/core-shop/tests/config/phpunit.xml --bootstrap vendor/coreshop/core-shop/tests/bootstrap.php vendor/coreshop/core-shop/tests/AllTests
