sudo: false
language: php
services:
    - redis

addons:
    mariadb: '10.1'
    hosts:
        - pimcore-test.dev
env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - CORESHOP_TEST=1
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/coreshop_test"
        - CORESHOP_SUITE=tests

matrix:
    include:
        - sudo: required
          php: 7.1
          env:
            - CORESHOP_SUITE=ecs

        - sudo: required
          php: 7.2
          env:
            - CORESHOP_SUITE=phpstan
            - PIMCORE_VERSION="5.5.3"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="5.4.4"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="5.4.4"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="5.5.0"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="5.5.0"

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="dev-master"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="dev-master"
    allow_failures:
        - env:
            - CORESHOP_SUITE=ecs
    fast_finish: true

cache:
    directories:
        - $HOME/.cache/composer

install:
    - etc/travis/install

script:
    - etc/travis/script

notifications:
    email:
        - travis-ci@coreshop.org