# This file is basically a copy of Pimcore's .travis.yml
# Actually, very dangerous, cause it depends on Pimcore's travis configuration files
# Which could be removed at any time from them

notifications:
    email:
        - travis-ci@coreshop.org

sudo: false
language: php

services:
    - redis

addons:
    mariadb: '10.1'
    hosts:
        - pimcore-test.dev

matrix:
    include:
        - os: linux
          sudo: required
          php: 7
          env: PIMCORE_BRANCH="tags/v5.1.0"

        - os: linux
          sudo: required
          php: 7.1
          env: PIMCORE_BRANCH="tags/v5.1.0"

        - os: linux
          sudo: required
          php: 7
          env: PIMCORE_BRANCH="tags/v5.1.1"

        - os: linux
          sudo: required
          php: 7.1
          env: PIMCORE_BRANCH="tags/v5.1.1"

        - os: linux
          sudo: required
          php: 7
          env: PIMCORE_BRANCH="tags/v5.1.2"

        - os: linux
          sudo: required
          php: 7.1
          env: PIMCORE_BRANCH="tags/v5.1.2"

        - os: linux
          sudo: required
          php: 7
          env: PIMCORE_BRANCH="tags/v5.1.3"

        - os: linux
          sudo: required
          php: 7.1
          env: PIMCORE_BRANCH="tags/v5.1.3"

        - os: linux
          sudo: required
          php: 7
          env: PIMCORE_BRANCH="master"

        - os: linux
          sudo: required
          php: 7.1
          env: PIMCORE_BRANCH="master"


env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - CORESHOP_TEST=1
        - CORESHOP_MYSQL_HOST=127.0.0.1
        - CORESHOP_MYSQL_DB=coreshop_phpunit
        - CORESHOP_MYSQL_USER=root
cache:
    directories:
        - ~/.composer/cache/files
        - vendor

before_install:
    - lib/CoreShop/bin/travis/setup/before_install

install:
    - lib/CoreShop/bin/travis/setup/install

script:
    - lib/CoreShop/bin/travis/setup/script
