imports:
  - { resource: "services/form.yml" }

services:
  coreshop.registry.shipping_rule.conditions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Component\Rule\Condition\ConditionCheckerInterface
      - shipping-rule-conditions

  coreshop.form_registry.shipping_rule.conditions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  coreshop.registry.shipping_rule.actions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Bundle\ShippingBundle\Rule\Action\CarrierPriceActionProcessorInterface
      - shipping-actions

  coreshop.form_registry.shipping_rule.actions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  # Shipping Rule Processor
  coreshop.shipping_rule.conditions.processor:
    class: CoreShop\Component\RuleBundle\Condition\RuleConditionsValidationProcessor
    shared: false
    arguments:
      - '@coreshop.registry.shipping_rule.conditions'

  coreshop.shipping_rule.processor:
    class: CoreShop\Component\RuleBundle\Condition\RuleValidationProcessor
    shared: false
    arguments:
      - '@coreshop.shipping_rule.conditions.processor'

  # Shipping CONDITIONS
  coreshop.shipping_rule.condition.amount:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\AmountConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: amount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\AmountConfigurationType }

  coreshop.shipping_rule.condition.categories:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\CategoriesConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: categories, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\CategoriesConfigurationType }

  coreshop.shipping_rule.condition.products:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: products, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\ProductsConfigurationType }

  coreshop.shipping_rule.condition.postcodes:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\PostcodeConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: postcodes, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\PostcodesConfigurationType }

  coreshop.shipping_rule.condition.weight:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\WeightConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: weight, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\WeightConfigurationType }

  coreshop.shipping_rule.condition.nested:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\NestedConditionChecker
    arguments: ['@coreshop.shipping_rule.processor', '@coreshop.repository.shipping_rule']
    tags:
      - { name: coreshop.shipping_rule.condition, type: conditions, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\NestedConfigurationType }

  coreshop.shipping_rule.condition.shipping_rule:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\ShippingRuleConditionChecker
    arguments: ['@coreshop.shipping_rule.processor', '@coreshop.repository.shipping_rule']
    tags:
      - { name: coreshop.shipping_rule.condition, type: shippingRule, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\ShippingRuleConfigurationType }

  # Shipping Rule ACTIONS
  coreshop.shipping_rule.action.price:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\PriceActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: price, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\PriceActionConfigurationType }
    arguments: ['@coreshop.taxation.factory.tax_calculator']

  coreshop.shipping_rule.action.addition_amount:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\AdditionAmountActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: additionAmount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\AdditionAmountActionConfigurationType }

  coreshop.shipping_rule.action.discount_amount:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\DiscountAmountActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\DiscountAmountActionConfigurationType }

  coreshop.shipping_rule.action.addition_percent:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\AdditionPercentActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: additionPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\AdditionPercentActionConfigurationType }

  coreshop.shipping_rule.action.discount_percent:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\DiscountPercentActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\DiscountPercentActionConfigurationType }

  coreshop.shipping_rule.action.shipping_rule:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\ShippingRuleActionProcessor
    arguments: ['@coreshop.carrier.processor.shipping_rules', '@coreshop.repository.shipping_rule']
    tags:
      - { name: coreshop.shipping_rule.action, type: shippingRule, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\ShippingRuleActionConfigurationType }


  # Carrier Price Calculator
  coreshop.carrier.processor.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Processor\ShippingRuleActionProcessor
    shared: false
    arguments:
      - '@coreshop.registry.shipping_rule.actions'

  coreshop.carrier.price_calculator.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierShippingRulePriceCalculator
    arguments:
      - '@coreshop.carrier.cart.checker'
      - '@coreshop.carrier.processor.shipping_rules'

  coreshop.carrier.price_calculator.default:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CompositePriceCalculator
    arguments: [['@coreshop.carrier.price_calculator.shipping_rules']]

  # Carrier Shipping Rule Validator
  coreshop.carrier.cart.checker:
    class: CoreShop\Bundle\ShippingBundle\Checker\CarrierShippingRuleChecker
    arguments: ['@coreshop.shipping_rule.processor']

  # Carrier Processor
  coreshop.carrier.cart.processor:
    class: CoreShop\Bundle\ShippingBundle\Processor\CartCarrierProcessor
    arguments: ['@coreshop.repository.carrier', '@coreshop.carrier.cart.checker']