imports:
  - { resource: "services/form.yml" }

services:
  coreshop.registry.shipping_rule.conditions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Bundle\ShippingBundle\Rule\Condition\ShippingConditionCheckerInterface
      - shipping-rule-conditions

  coreshop.form_registry.shipping_rule.conditions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  coreshop.registry.shipping_rule.actions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Bundle\ShippingBundle\Rule\Action\CarrierPriceActionProcessorInterface
      - shipping-actions

  coreshop.form_registry.shipping_rule.actions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  # Shipping Rule Processor
  coreshop.shipping_rule.processor:
    class: CoreShop\Component\RuleBundle\Condition\RuleValidationProcessor
    arguments:
      - '@coreshop.registry.shipping_rule.conditions'

  # Shipping CONDITIONS
  coreshop.shipping_rule.condition.amount:
    class: CoreShop\Bundle\ShippingBundle\Rule\Condition\AmountConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: amount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Condition\AmountConditionType }


  # Shipping Rule ACTIONS
  coreshop.shipping_rule.action.price:
    class: CoreShop\Bundle\ShippingBundle\Rule\Action\PriceActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: price, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Action\PriceActionType }
    arguments: ['@coreshop.taxation.factory.tax_calculator']

  # Carrier Price Calculator
  coreshop.carrier.price_calculator.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierShippingRulePriceCalculator
    arguments:
      - '@coreshop.carrier.cart.checker'
      - '@coreshop.registry.shipping_rule.actions'

  coreshop.carrier.price_calculator.default:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CompositePriceCalculator
    arguments: [['@coreshop.carrier.price_calculator.shipping_rules']]

  # Carrier Shipping Rule Validator
  coreshop.carrier.cart.checker:
    class: CoreShop\Bundle\ShippingBundle\Checker\CarrierShippingRuleChecker
    arguments: ['@coreshop.shipping_rule.processor']

  # Carrier Processor
  coreshop.carrier.cart.processor:
    class: CoreShop\Bundle\ShippingBundle\Processor\CartCarrierProcessor
    arguments: ['@coreshop.repository.carrier', '@coreshop.carrier.cart.checker']