services:
  coreshop.form.type.payment_provider_choice:
    class: CoreShop\Bundle\PaymentBundle\Form\Type\PaymentProviderChoiceType
    tags:
      - { name: form.type }
    arguments: ['@coreshop.repository.payment_provider']