parameters:
  coreshop.order.cart.folder_path: /%coreshop.core.object_path%/cart
  coreshop.order.order.folder_path: /%coreshop.core.object_path%/order
  coreshop.order.order_item.folder_path: items

services:
    coreshop.cart.manager:
      class: CoreShop\Bundle\OrderBundle\Manager\CartManager
      arguments:
        - '@coreshop.repository.cart'
        - '@coreshop.factory.cart'
        - '@session'
        - '@coreshop.core.object_service'
        - '@security.token_storage'
        - '%coreshop.order.cart.folder_path%'