services:
  coreshop.resource_controller.view_handler:
    class: CoreShop\Bundle\ResourceBundle\Controller\ViewHandler
    public: false
    arguments: ['@jms_serializer']

  coreshop.resource_controller.parameters_parser:
    class: CoreShop\Bundle\ResourceBundle\Controller\ParametersParser
    arguments: ['@service_container', '@coreshop.expression_language']

  coreshop.resource_controller.request_configuration_factory:
    class: CoreShop\Bundle\ResourceBundle\Controller\RequestConfigurationFactory
    public: false
    arguments: ['@coreshop.resource_controller.parameters_parser', CoreShop\Bundle\ResourceBundle\Controller\RequestConfiguration, '%coreshop.resource.settings%']
  
  coreshop.resource_controller.new_resource_factory:
    class: CoreShop\Bundle\ResourceBundle\Controller\NewResourceFactory
    public: false
  
  coreshop.resource_controller.single_resource_provider:
    class: CoreShop\Bundle\ResourceBundle\Controller\SingleResourceProvider
    public: false
  
  coreshop.resource_controller.resources_resolver:
    class: CoreShop\Bundle\ResourceBundle\Controller\ResourcesResolver
    public: false
  
  coreshop.resource_controller.resources_collection_provider:
    class: CoreShop\Bundle\ResourceBundle\Controller\ResourcesCollectionProvider
    public: false
    arguments: ['@coreshop.resource_controller.resources_resolver']
  
  coreshop.resource_controller.form_factory:
    class: CoreShop\Bundle\ResourceBundle\Controller\ResourceFormFactory
    public: false
    arguments: ['@form.factory']
  
  coreshop.resource_controller.redirect_handler:
    class: CoreShop\Bundle\ResourceBundle\Controller\RedirectHandler
    public: false
    arguments: ['@router']

  coreshop.resource_controller.flash_helper:
    class: CoreShop\Bundle\ResourceBundle\Controller\FlashHelper
    public: false
    arguments: ['@session', '@translator', '%locale%']
  
  coreshop.resource_controller.event_dispatcher:
    class: CoreShop\Bundle\ResourceBundle\Controller\EventDispatcher
    public: false
    arguments: ['@event_dispatcher']
  
  coreshop.resource_controller.view_handler:
    class: CoreShop\Bundle\ResourceBundle\Controller\ViewHandler
    public: false
    arguments: ['@fos_rest.view_handler']

  coreshop.resource_controller.resource_update_handler:
    class: CoreShop\Bundle\ResourceBundle\Controller\ResourceUpdateHandler
    public: false