services:
  coreshop.resource_controller.view_handler:
    class: CoreShop\Bundle\ResourceBundle\Controller\ViewHandler
    public: false
    arguments: ['@jms_serializer']

  coreshop.resource_controller.event_dispatcher:
    class: CoreShop\Bundle\ResourceBundle\Controller\EventDispatcher
    public: false
    arguments: ['@event_dispatcher']