default:
    suites:
        domain_taxation:
            contexts_services:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - coreshop.behat.context.hook.doctrine_orm
                - coreshop.behat.context.hook.pimcore_dao

                - coreshop.behat.context.transform.shared_storage
                - coreshop.behat.context.transform.tax_rate
                - coreshop.behat.context.transform.store
                - coreshop.behat.context.transform.country

                - coreshop.behat.context.setup.tax_rate
                - coreshop.behat.context.setup.store
                - coreshop.behat.context.setup.country

                - coreshop.behat.context.domain.tax_rate
            filters:
                tags: "@taxation"