imports:
  - { resource: "services/form.yml" }
  - { resource: "services/price-rules.yml" }
  - { resource: "services/specific-price-rules.yml" }

services:
  # Product Price Rule CONDITIONS
  coreshop.product_price_rule.condition.products:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: products, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

  coreshop.product_price_rule.condition.nested:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\NestedConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: conditions, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\NestedConfigurationType }
      - { name: coreshop.product_specific_price_rule.condition, type: conditions, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\NestedConfigurationType }

  coreshop.product_price_rule.condition.categories:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\CategoriesConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: categories, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\CategoriesConfigurationType }

  coreshop.product_price_rule.condition.timespan:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\TimeSpanConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: timespan, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\TimespanConfigurationType }
      - { name: coreshop.product_specific_price_rule.condition, type: timespan, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\TimespanConfigurationType }

  # Product Price Rule ACTIONS
  coreshop.product_price_rule.action.price:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\PriceActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: price, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\PriceConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: price, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\PriceConfigurationType }

  coreshop.product_price_rule.action.discount_amount:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\DiscountAmountActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountAmountConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountAmountConfigurationType }

  coreshop.product_price_rule.action.discount_percent:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\DiscountPercentActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountPercentConfigurationType }
      - { name: coreshop.product_specific_price_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\DiscountPercentConfigurationType }

  # Price Calculators
  coreshop.product.price_calculator.property_price:
    class: CoreShop\Bundle\ProductBundle\Calculator\PropertyPriceCalculator

  coreshop.product.price_calculator.default:
    class: CoreShop\Bundle\ProductBundle\Calculator\CompositePriceCalculator
    arguments:
      - ['@coreshop.product.price_calculator.property_price', '@coreshop.product.price_calculator.product_price_rules', '@coreshop.product.price_calculator.product_specific_price_rules']

  coreshop.product.price_calculator:
    alias: coreshop.product.price_calculator.default