imports:
  - { resource: "services/form.yml" }

services:
  coreshop.registry.product_price_rule.conditions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Component\Rule\Condition\ConditionCheckerInterface
      - product-price-rule-conditions

  coreshop.form_registry.product_price_rule.conditions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  coreshop.registry.product_price_rule.actions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Component\Product\Rule\Action\ProductPriceActionProcessorInterface
      - product-price-rule-actions

  coreshop.form_registry.product_price_rule.actions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  # Price Rule Processor
  coreshop.product_price_rule.processor:
    class: CoreShop\Component\Rule\Condition\RuleValidationProcessor
    arguments:
      - '@coreshop.registry.product_price_rule.conditions'

  # Product Price Rule CONDITIONS
  coreshop.product_price_rule.condition.quantity:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\QuantityConditionChecker
    arguments:
      - '@coreshop.cart.manager'
    tags:
      - { name: coreshop.product_price_rule.condition, type: quantity, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\QuantityConfigurationType }

  coreshop.product_price_rule.condition.products:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: products, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

  coreshop.product_price_rule.condition.nested:
    class: CoreShop\Bundle\ProductBundle\Rule\Condition\NestedConditionChecker
    tags:
      - { name: coreshop.product_price_rule.condition, type: conditions, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Condition\NestedConfigurationType }

  # Product Price Rule ACTIONS
  coreshop.product_price_rule.action.discount:
    class: CoreShop\Bundle\ProductBundle\Rule\Action\NewPriceActionProcessor
    tags:
      - { name: coreshop.product_price_rule.action, type: newPrice, form-type: CoreShop\Bundle\ProductBundle\Form\Type\Rule\Action\NewPriceConfigurationType }


  # Price Calculators
  coreshop.product.price_calculator.product_price_rules:
    class: CoreShop\Bundle\ProductBundle\Calculator\ProductPriceRuleCalculator
    arguments:
      - '@coreshop.repository.product_price_rule'
      - '@coreshop.product_price_rule.processor'
      - '@coreshop.registry.product_price_rule.actions'

  coreshop.product.price_calculator.property_price:
    class: CoreShop\Bundle\ProductBundle\Calculator\PropertyPriceCalculator

  coreshop.product.price_calculator.default:
    class: CoreShop\Bundle\ProductBundle\Calculator\CompositePriceCalculator
    arguments:
      - ['@coreshop.product.price_calculator.property_price', '@coreshop.product.price_calculator.product_price_rules']

  coreshop.product.price_calculator:
    alias: coreshop.product.price_calculator.default