imports:
    - { resource: "services/routing.yml" }
    - { resource: "services/controller.yml" }

parameters:
  jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
  coreshop.resource_registry:
    class: CoreShop\Component\Resource\Metadata\Registry
    public: false


  coreshop.jms_serializer.handler.relation:
      class: CoreShop\Bundle\ResourceBundle\Serialization\RelationsHandler
      arguments:
      - "@doctrine.orm.entity_manager"
      tags:
      - { name: jms_serializer.handler, type: relation, direction: serialization, format: json, method: serializeRelation}
      - { name: jms_serializer.handler, type: relation, direction: deserialization, format: json, method: deserializeRelation}
      - { name: jms_serializer.handler, type: relation<?>, direction: serialization, format: json, method: serializeRelation}
      - { name: jms_serializer.handler, type: relation<?>, direction: deserialization, format: json, method: deserializeRelation}

  jms_serializer.object_constructor:
    alias: jms_serializer.doctrine_object_constructor
    public: false