services:
  coreshop.frontend.controller.customer:
    class: CoreShop\Bundle\FrontendBundle\Controller\CustomerController
    calls:
            - [setContainer, ['@service_container']]

  coreshop.frontend.controller.currency:
    class: CoreShop\Bundle\FrontendBundle\Controller\CurrencyController
    calls:
            - [setContainer, ['@service_container']]

  coreshop.frontend.controller.language:
    class: CoreShop\Bundle\FrontendBundle\Controller\LanguageController
    calls:
            - [setContainer, ['@service_container']]

  coreshop.frontend.controller.search:
    class: CoreShop\Bundle\FrontendBundle\Controller\SearchController
    calls:
            - [setContainer, ['@service_container']]

  coreshop.frontend.controller.cart:
    class: CoreShop\Bundle\FrontendBundle\Controller\CartController
    calls:
            - [setContainer, ['@service_container']]

  coreshop.frontend.controller.category:
    alias: coreshop.pimcore_controller.category

  coreshop.frontend.controller.product:
    alias: coreshop.pimcore_controller.product