CoreShop\Component\TierPricing\Model\ProductTierPriceRange:
    type: mappedSuperclass
    table: coreshop_product_tier_price_range
    fields:
        id:
            column: id
            type: integer
            id: true
            generator:
                strategy: AUTO
        rangeFrom:
            column: range_from
            type: integer
        rangeTo:
            column: range_to
            type: integer
        pricingBehaviour:
            column: pricing_behaviour
            type: string
        amount:
            column: amount
            type: integer
        percentage:
            column: percentage
            type: float
        pseudoPrice:
            column: pseudo_price
            type: integer
        highlighted:
            column: highlighted
            type: boolean
    manyToOne:
        currency:
            targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
            joinColumn:
                name: currencyId
                referencedColumnName: id
                onDelete: 'SET NULL'