CoreShop\Component\TierPricing\Model\ProductTierPrice:
    type: mappedSuperclass
    table: coreshop_product_tier_price
    fields:
        id:
            column: id
            type: integer
            id: true
            generator:
                strategy: AUTO
        active:
            column: active
            type: boolean
            options:
                default: 1
        product:
            column: productId
            type: pimcoreObject
        property:
            column: property
            type: string
    oneToMany:
        ranges:
            targetEntity: CoreShop\Component\TierPricing\Model\ProductTierPriceRangeInterface
            mappedBy: tierPrice
            orphanRemoval: true
            cascade:
                - all
    manyToOne:
        store:
            targetEntity: CoreShop\Component\Store\Model\StoreInterface
            joinColumn:
                name: store_id
                referencedColumnName: id
                onDelete: 'SET NULL'