CoreShop\Component\TierPricing\Model\ProductTierPriceRange:
    type: mappedSuperclass
    table: coreshop_product_tier_price_range
    fields:
        id:
            column: id
            type: integer
            id: true
            generator:
                strategy: AUTO
        rangeFrom:
            column: range_from
            type: integer
        rangeTo:
            column: range_to
            type: integer
        price:
            column: price
            type: integer
        percentageDiscount:
            column: percentage_discount
            type: float
        highlighted:
            column: highlighted
            type: boolean