imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: 'local/' }
    - { resource: "@CoreShopCoreBundle/Resources/config/app/config.yml" }
