jms_serializer:
    metadata:
        directories:
            coreshop-address:
                namespace_prefix: "CoreShop\\Component\\Shipping"
                path: "@CoreShopShippingBundle/Resources/config/serializer"
