imports:
  - { resource: "services/form.yml" }


services:
  coreshop.context.store.composite:
      class: CoreShop\Component\Store\Context\CompositeStoreContext
      public: false

  coreshop.context.store.request_based:
      class: CoreShop\Component\Store\Context\RequestBased\StoreContext
      public: false
      tags:
          - { name: coreshop.context.store }
      arguments: ['@coreshop.context.store.request_based.resolver', '@request_stack']

  coreshop.context.store.request_based.resolver.composite:
      class: CoreShop\Component\Store\Context\RequestBased\CompositeRequestResolver
      public: false

  coreshop.context.store.request_based.resolver.hostname_based:
      class: CoreShop\Component\Store\Context\RequestBased\SiteBasedRequestResolver
      public: false
      tags:
          - { name: coreshop.context.store.request_based.resolver }
      arguments: ['@coreshop.repository.store']

