payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"


coreshop_admin_payment_provider_config:
  path: /%coreshop.admin.route.base%/payment_providers/get-config
  defaults: { _controller: 'coreshop.admin_controller.payment_provider:getConfigAction'}

coreshop_order_get_grid_configuration:
  path: /%coreshop.admin.route.base%/order/get-order-grid-configuration
  defaults: { _controller: 'coreshop.pimcore_controller.order:getOrderGridConfigurationAction'}

coreshop_order_get_orders:
  path: /%coreshop.admin.route.base%/order/get-orders
  defaults: { _controller: 'coreshop.pimcore_controller.order:getOrders'}

coreshop_order_get_order:
  path: /%coreshop.admin.route.base%/order/detail
  defaults: { _controller: 'coreshop.pimcore_controller.order:detailAction'}

coreshop_admin_configuration_save_all:
  path: /%coreshop.admin.route.base%/configurations/save-all
  defaults: { _controller: 'coreshop.admin_controller.configuration:saveAllAction'}

coreshop_admin_configuration_get_all:
  path: /%coreshop.admin.route.base%/configurations/get-all
  defaults: { _controller: 'coreshop.admin_controller.configuration:getAllAction'}