imports:
    - { resource: 'services/rules.yml' }
    - { resource: 'services/specific-tier-price-rules.yml' }
    - { resource: 'services/actions.yml' }

services:
    coreshop.templating.helper.tier_pricing:
        class: CoreShop\Bundle\TierPricingBundle\Templating\Helper\TierPricingHelper
        arguments:
            - '@coreshop.context.shopper'
            - '@coreshop.tier_pricing.price_calculator.product_specific_tier_price_rules'
        tags:
            - { name: templating.helper, alias: coreshop_tier_price }

    coreshop.twig.extension.tier_pricing:
        class: CoreShop\Bundle\TierPricingBundle\Twig\TierPricingExtension
        public: false
        arguments:
            - '@coreshop.templating.helper.tier_pricing'
        tags:
            - { name: twig.extension }

    coreshop.tier_pricing.locator.tier_price:
        class: CoreShop\Component\TierPricing\Locator\TierPriceLocator

