imports:
    #- { resource: "@CoreShopAddressBundle/Resources/config/app/config.yml" }
    #- { resource: "@CoreShopConfiguration/Resources/config/app/config.yml" }
    #- { resource: "@CoreShopCurrencyBundle/Resources/config/app/config.yml" }
    #- { resource: "@CoreShopCustomerBundle/Resources/config/app/config.yml" }
    #- { resource: "@CoreShopStoreBundle/Resources/config/app/config.yml" }
    #- { resource: "@CoreShopTaxationBundle/Resources/config/app/config.yml" }

    - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop.yml" }

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
