imports:
    - { resource: "@CoreShopResourceBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopAddressBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopCurrencyBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopStoreBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopTaxationBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopProductBundle/Resources/config/app/config.yml" }
    - { resource: "@CoreShopIndexBundle/Resources/config/app/config.yml" }

    - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop.yml" }

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

jms_serializer:
    metadata:
        directories:
            core-shop-core:
                namespace_prefix: "CoreShop\\Component\\Core"
                path: "@CoreShopCoreBundle/Resources/config/serializer"

fos_rest:
    format_listener:
        rules:
            - { path: '^/admin/CoreShop', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }