imports:
    - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop/coreshop_address.yml" }
    - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop/coreshop_taxation.yml" }
    - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop/coreshop_currency.yml" }