services:
    coreshop.behat.context.domain.product:
        class: CoreShop\Behat\Context\Domain\ProductContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.product'
            - '@__symfony__.coreshop.product.price_calculator'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.domain.product_specific_price_rule:
        class: CoreShop\Behat\Context\Domain\ProductSpecificPriceRuleContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.product_specific_price_rule.processor'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.domain.product_price_rule:
        class: CoreShop\Behat\Context\Domain\ProductPriceRuleContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.product_price_rule.processor'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.domain.customer:
        class: CoreShop\Behat\Context\Domain\CustomerContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.context.customer'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.domain.currency:
        class: CoreShop\Behat\Context\Domain\CurrencyContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.context.currency'
        tags:
            - { name: fob.context_service }
