services:
    coreshop.behat.context.domain.product:
        class: CoreShop\Behat\Context\Domain\ProductContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.product'
            - '@__symfony__.coreshop.product.price_calculator'
        tags:
            - { name: fob.context_service }
