services:
    coreshop.behat.context.transform.shared_storage:
        class: CoreShop\Behat\Context\Transform\SharedStorageContext
        arguments:
            - '@coreshop.behat.shared_storage'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.product:
        class: CoreShop\Behat\Context\Transform\ProductContext
        arguments:
            - '@__symfony__.coreshop.repository.product'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.category:
        class: CoreShop\Behat\Context\Transform\CategoryContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.category'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.product_specific_price_rule:
        class: CoreShop\Behat\Context\Transform\ProductSpecificPriceRuleContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.product_specific_price_rule'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.product_price_rule:
        class: CoreShop\Behat\Context\Transform\ProductPriceRuleContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.product_price_rule'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.country:
        class: CoreShop\Behat\Context\Transform\CountryContext
        arguments:
            - '@__symfony__.coreshop.repository.country'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.currency:
        class: CoreShop\Behat\Context\Transform\CurrencyContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.currency'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.customer:
        class: CoreShop\Behat\Context\Transform\CustomerContext
        arguments:
            - '@__symfony__.coreshop.repository.customer'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.customer_group:
        class: CoreShop\Behat\Context\Transform\CustomerGroupContext
        arguments:
            - '@__symfony__.coreshop.repository.customer_group'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.zone:
        class: CoreShop\Behat\Context\Transform\ZoneContext
        arguments:
            - '@__symfony__.coreshop.repository.zone'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.store:
        class: CoreShop\Behat\Context\Transform\StoreContext
        arguments:
            - '@__symfony__.coreshop.repository.store'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.tax_rate:
        class: CoreShop\Behat\Context\Transform\TaxRateContext
        arguments:
            - '@__symfony__.coreshop.repository.tax_rate'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.transform.tax_rule_group:
        class: CoreShop\Behat\Context\Transform\TaxRuleGroupContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@__symfony__.coreshop.repository.tax_rule_group'
        tags:
            - { name: fob.context_service }
