imports:
    - { resource: "services/form.yml" }

parameters:
  coreshop.payment.folder_path: payments

services:
 coreshop.frontend.controller.payment:
    class: CoreShop\Bundle\PayumBundle\Controller\PaymentController
    arguments:
      - '@coreshop.factory.payment'
      - '@coreshop.repository.order'
      - '%coreshop.payment.folder_path%'
      - '@coreshop.core.object_service'
      - '@coreshop.context.currency'
    calls:
            - [setContainer, ['@service_container']]