CoreShop\Component\Core\Model\PaymentProvider:
  type: mappedSuperclass
  table: coreshop_tax_rule_group
  manyToMany:
    stores:
      targetEntity: CoreShop\Component\Store\Model\StoreInterface
      joinTable:
        name: coreshop_tax_rule_group_stores
        joinColumns:
          payment_method_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
  manyToOne:
    paymentProviderConfig:
      targetEntity: CoreShop\Bundle\PayumBundle\Model\PaymentProviderConfig
      joinColumn:
        name: payment_provider_config_id
        referencedColumnName: id
        nullable: true
        onDelete: "SET NULL"
