CoreShop\Component\Core\Model\TaxRule:
  type: mappedSuperclass
  table: coreshop_tax_rule
  manyToOne:
    country:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      inversedBy: taxRules
      joinColumn:
        name: countryId
        referencedColumnName: id
        nullable: true
    state:
      targetEntity: CoreShop\Component\Address\Model\StateInterface
      inversedBy: taxRules
      joinColumn:
        name: stateId
        referencedColumnName: id
        nullable: true