imports:
  - { resource: "services/form.yml" }

services:
  coreshop.currency_collector:
    class: CoreShop\Bundle\CurrencyBundle\Collector\CurrencyCollector
    arguments: ['@coreshop.repository.currency', '@coreshop.context.currency', '@coreshop.context.store', false]
    tags:
      - { name: data_collector, template: 'CoreShopCurrencyBundle:Collector:currency.html.twig', id: coreshop.currency_collector}