services:
    _defaults:
        public: true

    coreshop.tier_pricing.condition.nested:
        class: CoreShop\Component\Rule\Condition\NestedConditionChecker
        arguments:
            - '@coreshop.product_specific_tier_price_rule.conditions.processor'
        tags:
            - { name: coreshop.product_specific_tier_price_rule.condition, type: nested, form-type: CoreShop\Bundle\TierPricingBundle\Form\Type\Rule\Condition\ProductSpecificTierPriceNestedConfigurationType }
