default:
    suites:
        domain_products:
            contexts_services:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - coreshop.behat.context.hook.doctrine_orm
                - coreshop.behat.context.hook.pimcore_dao

                - coreshop.behat.context.transform.shared_storage
                - coreshop.behat.context.transform.product
                - coreshop.behat.context.transform.product_specific_price_rule
                - coreshop.behat.context.transform.category
                - coreshop.behat.context.transform.country
                - coreshop.behat.context.transform.currency
                - coreshop.behat.context.transform.customer

                - coreshop.behat.context.setup.product
                - coreshop.behat.context.setup.product_specific_price_rule
                - coreshop.behat.context.setup.store
                - coreshop.behat.context.setup.category
                - coreshop.behat.context.setup.country
                - coreshop.behat.context.setup.currency
                - coreshop.behat.context.setup.customer

                - coreshop.behat.context.domain.product
                - coreshop.behat.context.domain.product_specific_price_rule
                - coreshop.behat.context.domain.customer
