imports:
    - suites/domain/product.yml
    - suites/domain/currency.yml
    - suites/domain/taxation.yml
    - suites/domain/cart.yml
    - suites/domain/category.yml
    - suites/domain/shipping.yml
    - suites/domain/country.yml
    - suites/domain/index.yml
