default:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        FriendsOfBehat\SymfonyExtension:
            kernel:
                class: TestAppKernel
                path: lib/CoreShop/behat/app/TestAppKernel.php
                bootstrap: lib/CoreShop/behat/bootstrap.php

        FriendsOfBehat\ContextServiceExtension:
            imports:
                - "src/CoreShop/Behat/Resources/config/services.yml"

        FriendsOfBehat\CrossContainerExtension: ~

        FriendsOfBehat\VariadicExtension: ~
