CoreShop\Component\Addressing\Model\State:
  exclusion_policy: ALL
  xml_root_name: state
  properties:
    id:
      expose: true
      type: integer
      xml_attribute: true
      groups: [List, Detailed]
    isoCode:
      expose: true
      type: string
      groups: [Detailed]
    name:
      expose: true
      type: string
      groups: [List, Detailed]
    active:
      expose: true
      type: boolean
      groups: [List, Detailed]