CoreShop\Component\Address\Model\Zone:
  exclusion_policy: ALL
  xml_root_name: zone
  properties:
    id:
      expose: true
      type: integer
      xml_attribute: true
    name:
      expose: true
      type: string
    active:
      expose: true
      type: boolean
    countries:
      expose: true
      type: relation
