imports:
  - { resource: "services/context.yml" }
  - { resource: "services/storage.yml" }
  - { resource: "services/form.yml" }
  - { resource: "services/checkout.yml" }

parameters:
  coreshop.core.object_path: '/coreshop'

services:
  coreshop.core.object_service:
    class: CoreShop\Component\Core\Pimcore\ObjectService

  coreshop.context.locale.composite:
    class: CoreShop\Component\Core\Context\CompositeLocaleContext
    decorates: coreshop.context.locale
    decoration_priority: 256
    public: false

  coreshop.context.locale.pimcore:
    class: CoreShop\Component\Core\Context\PimcoreLocaleContext
    arguments: ['@pimcore.locale']
    tags:
      - { name: coreshop.context.locale }

  coreshop.taxation.factory.tax_calculator:
    class: CoreShop\Bundle\CoreBundle\Taxation\TaxCalculatorFactory
    arguments: ['@coreshop.repository.tax_rule']

  coreshop.security.customer.user_provider:
    class: Pimcore\Security\User\ObjectUserProvider
    arguments: ['%coreshop.model.customer.class%', 'email']

  coreshop.security.customer.password_encoder_factory:
    class: Pimcore\Security\Encoder\Factory\UserAwareEncoderFactory
    arguments:
      - Pimcore\Security\Encoder\PasswordFieldEncoder
      - ['password']