imports:
  - { resource: "services/context.yml" }
  - { resource: "services/storage.yml" }
  - { resource: "services/form.yml" }

parameters:
  coreshop.core.object_path: '/coreshop'

services:
  coreshop.core.object_service:
    class: CoreShop\Component\Core\Pimcore\ObjectService