parameters:
  coreshop.form.type.product_price_rule.validation_groups: [coreshop]

services:
  coreshop.form.type.product_price_rule:
    class: CoreShop\Bundle\ProductBundle\Form\Type\ProductPriceRuleType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.product_price_rule.class%', '%coreshop.form.type.product_price_rule.validation_groups%']