services:
  coreshop.context.shopper:
    class: CoreShop\Component\Core\Context\ShopperContext
    lazy: true
    arguments: ['@coreshop.context.store', '@coreshop.context.currency']

  coreshop.storage.currency:
    class: CoreShop\Component\Core\Currency\CurrencyStorage
    arguments:
      - '@coreshop.storage.cookie'
      - '@coreshop.repository.country'

  coreshop.context.currency.storage_based:
    class: CoreShop\Component\Core\Currency\Context\StorageBasedCurrencyContext
    arguments:
      - '@coreshop.context.store'
      - '@coreshop.storage.currency'
    tags:
      - { name: 'coreshop.context.currency' }

  coreshop.context.currency.store_aware:
    class: CoreShop\Component\Core\Currency\Context\StoreAwareCurrencyContext
    decorates: coreshop.context.currency
    decoration_priority: 256
    arguments: ['@coreshop.context.currency.store_aware.inner', '@coreshop.context.store', '@coreshop.repository.country']