services:
  coreshop.order.number_generator.default:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\OrderNumberGenerator
    arguments: ['@coreshop.sequence.generator', 'order', '@coreshop.configuration.service']

  coreshop.order.transformer.cart_item_to_order_item:
    class: CoreShop\Component\Core\Transformer\CartItemToOrderItemTransformer
    arguments:
      - '@coreshop.core.object_service'
      - '%coreshop.folder.order_item%'

  coreshop.order.transformer.cart_to_order:
    class: CoreShop\Component\Core\Transformer\CartToOrderTransformer
    arguments:
      - '@coreshop.order.transformer.cart_item_to_order_item'
      - '@coreshop.core.key_transformer'
      - '@coreshop.order.number_generator.default'
      - '%coreshop.folder.order%'
      - '@coreshop.core.object_service'
      - '@coreshop.context.locale'
      - '@coreshop.factory.order_item'
      - '@coreshop.context.currency'
      - '@coreshop.context.store'
      - '@coreshop.cart_price_rule.order.processor'

  coreshop.factory.cart:
    class: CoreShop\Bundle\CoreBundle\Factory\CartFactory
    arguments:
      - '%coreshop.model.cart.class%'
      - '@coreshop.context.currency'
      - '@coreshop.context.store'

  coreshop.mail.processor.order:
    class: CoreShop\Component\Core\Order\OrderMailProcessor
    arguments: ['@coreshop.money_formatter', '@coreshop.repository.order_invoice']