services:
  coreshop.order.number_generator.default:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\SequenceNumberGenerator
    arguments: ['@coreshop.sequence.generator', 'order']

  coreshop.order.transformer.cart_item_to_order_item:
    class: CoreShop\Component\Core\Transformer\CartItemToOrderItemTransformer
    arguments:
      - '@coreshop.core.object_service'
      - '%coreshop.order.order_item.folder_path%'

  coreshop.order.transformer.cart_to_order:
    class: CoreShop\Component\Core\Transformer\CartToOrderTransformer
    arguments:
      - '@coreshop.order.transformer.cart_item_to_order_item'
      - '@coreshop.core.key_transformer'
      - '@coreshop.order.number_generator.default'
      - '%coreshop.order.order.folder_path%'
      - '@coreshop.core.object_service'
      - '@coreshop.context.locale'
      - '@coreshop.factory.order_item'
      - '@coreshop.context.currency'
      - '@coreshop.context.store'
      - '@coreshop.cart_price_rule.order.processor'