services:
  coreshop.carrier.price_calculator.free_shipping_rule:
    class: CoreShop\Bundle\CoreBundle\Shipping\Calculator\FreeShippingPriceRuleActionCalculator
    tags:
      - { name: coreshop.shipping.price_calculator, type: free-shipping-rule, priority: 255 }
