services:
  coreshop.shipping_rule.condition.customers:
    class: CoreShop\Bundle\CoreBundle\Product\Rule\Condition\CustomersConditionChecker
    arguments:
      ['@security.token_storage']
    tags:
      - { name: coreshop.shipping_rule.condition, type: customers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomersConfigurationType }

  coreshop.shipping_rule.condition.countries:
    class: CoreShop\Bundle\CoreBundle\Product\Rule\Condition\CountriesConditionChecker
    arguments:
      ['@coreshop.context.country']
    tags:
      - { name: coreshop.shipping_rule.condition, type: countries, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CountriesConfigurationType }

  coreshop.shipping_rule.condition.zones:
    class: CoreShop\Bundle\CoreBundle\Product\Rule\Condition\ZonesConditionChecker
    arguments:
      ['@coreshop.context.country']
    tags:
      - { name: coreshop.shipping_rule.condition, type: zones, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ZonesConfigurationType }

  coreshop.shipping_rule.condition.stores:
    class: CoreShop\Bundle\CoreBundle\Product\Rule\Condition\StoresConditionChecker
    arguments:
      ['@coreshop.context.store']
    tags:
      - { name: coreshop.shipping_rule.condition, type: stores, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\StoresConfigurationType }

  coreshop.shipping_rule.condition.currencies:
    class: CoreShop\Bundle\CoreBundle\Product\Rule\Condition\CurrenciesConditionChecker
    arguments:
      ['@coreshop.context.currency']
    tags:
      - { name: coreshop.shipping_rule.condition, type: currencies, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CurrenciesConfigurationType }