core_shop_taxation:
  resources:
    tax_rule:
      classes:
        model: CoreShop\Component\Core\Model\TaxRule
    tax_rule_group:
      classes:
        model: CoreShop\Component\Core\Model\TaxRuleGroup